# Configuration file for automatic testing at travis-ci.org

sudo: false

language: python

python:
  - "2.7"
  - "3.4"
  - "3.5"
  - "3.6"

addons:
  apt:
    packages:
      - graphviz  # sphinx inheritance diagrams
      # - texlive-latex-base  # pdf from sphinx latex
      # - texlive-latex-recommended
      # - texlive-latex-extra
      # - texlive-fonts-recommended
      # - latexmk

install:
  - pip install --upgrade pip
  - pip install -r requirements.txt
  - pip install coveralls
  - python setup.py install
  - mkdir -p ~/.config/matplotlib
  - "echo backend : agg > ~/.config/matplotlib/matplotlibrc"

script:
  - make lint
  - make test
  - make docall

after_success:
  - coveralls
