# Needed as trusty (the default) doesn't support python 3.7.
# Remove once xenial is made default.
# https://github.com/travis-ci/travis-ci/issues/9815
dist: xenial

language: python

python:
  - 2.7
  - 3.5
  - 3.6
  - 3.7

addons:
  apt:
    packages:
      - graphviz  # sphinx inheritance diagrams

install:
  - pip install -U --upgrade-strategy eager .[test,doc]
  # Update dependencies (e.g. numpy formatting changed in v1.14).

script:
  - make lint
  - make test
  - make doc

after_success:
  - coveralls
