language: python

python:
  - 2.7
  - 3.4
  - 3.5
  - 3.6

addons:
  apt:
    packages:
      - graphviz  # sphinx inheritance diagrams

install:
  - pip install -U --upgrade-strategy eager .[test,doc]
  # Update dependencies (e.g. numpy formatting changed in v1.14).
  - mkdir -p ~/.config/matplotlib
  - "echo backend : agg > ~/.config/matplotlib/matplotlibrc"

script:
  - make lint
  - make test
  - make doc

after_success:
  - coveralls
